version: '2'
services:
    twentyonepoints-app:
        image: twentyonepoints
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://twentyonepoints-postgresql:5432/TwentyOnePoints
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=twentyonepoints-elasticsearch:9300
        ports:
            - 8080:8080
    twentyonepoints-postgresql:
        extends:
            file: postgresql.yml
            service: twentyonepoints-postgresql
    twentyonepoints-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: twentyonepoints-elasticsearch
