version: '2'
services:
    21points-elasticsearch:
        container_name: 21points-elasticsearch
        image: elasticsearch:2.4.0
        # volumes:
        #     - ~/volumes/jhipster/21points/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
